### ISSUE TITLE
Some OS's use libudev.so.1 and not libudev.so.0

### ISSUE THREAD

**Issue by JBKahn** [plaidchat/plaidchat#1]
The proposed solution worked for me. Perhaps an addition to the README if you're interested in adding that. 

http://askubuntu.com/questions/330935/error-while-loading-shared-libraries-libudev-so-0-brackets

Otherwise it just gave me this message when I went to run it

`./resources/node-webkit/Linux64/nw: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory`

**Comment by wlaurance** [comment]
Until there is an official fix in node-webkit, I think we should add some logic to the install script to check for the existence of the proper lib.

See #16
