### ISSUE TITLE
Sharing some numbers

### ISSUE THREAD

**Issue by wlaurance** [plaidchat/plaidchat#101]
![screenshot_2015-06-29_13-46-38](https://cloud.githubusercontent.com/assets/1059214/8418063/7aff4fd0-1e65-11e5-8381-58ed93cfa31e.png)

**Comment by mathieumg** [comment]
I figure those are for the "project page" here on GitHub?

**Comment by wlaurance** [comment]
Yes these are the page views for the README

**Comment by twolfson** [comment]
Thanks for sharing. It would be great if there was a way to make the information public but after doing some research it looks like Google Analytics only supports template sharing or exporting via an API =(
