### ISSUE TITLE
plaidchat.desktop entry

### ISSUE THREAD

**Issue by rosshadden** [plaidchat/plaidchat#102]
It would be great to have a `plaidchat.desktop` entry.  I forked to add one myself, but it's a little weird because it's a node binary, which
1. isn't in the `PATH` of the system (at least when your `npm` is configured to be per-user (as it should be)
2. can be different for different machines and users.  For example, mine is at `~/local/bin/plaidchat`

I'm sure there's a best-practice for making `*.desktop` files for nw.js apps.  I'll look into it when I get a chance.

**Comment by twolfson** [comment]
I believe the best practice would be to create a `.deb` and `.rpm` (#13) and then bundle the `plaidchat.desktop` when a global installation occurs.

For the interim, we should be able to resolve the path of `plaidchat` via a utility such as `which` (there are also cross-platform node solutions for this). As for installing the `.desktop` to global/local, I think we should aim for the typical case of global installation to `/usr/local/lib`

**Comment by rosshadden** [comment]
Yeah I think it's fine to use `which plaidchat` and `/usr/share//applications/plaidchat.desktop`, until we have something more robust.  I'll probably do that within the next few days and make a PR, which will be linked to and close this issue.

**Comment by twolfson** [comment]
`npm` has a `postinstall` hook which should have `plaidchat` on the `PATH` by the end of it. I would imagine at that point, we perform a `which plaidchat` and then run that filepath through a templater to generate a `.desktop` file for the current machine.

**Comment by GrayedFox** [comment]
hey, thought this might be the appropriate place to post this question (although I can create another issue if necessary). I went ahead and made a .desktop file with these settings:
```
[Desktop Entry]
Version=1.0
Name=Plaidchat
Comment=A Slack Interface for Linux
GenericName=Plaidchatnau
Keywords=Slack;Plaidchat
Exec=plaidchat %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=slack256.png
StartupNotify=true
Name[en_US]=Plaidchat
```
However I cannot log in. Not sure if it's a network thing or if I have specified the wrong settings in the desktop file. If they are wrong, I also figure this issue would be a good place to have a template .desktop file for those looking to create/use one. Oh... and please excuse the use of the Slack icon - will gladly use a Plaidchat icon once we have one!

**Comment by rosshadden** [comment]
@twolfson I don't need to use a full path when I use a local `.desktop` file (I had originally tried a system-level one).  But my `npm` modules are all installed locally, so that is expected.

I'm not sure what the best practice would be for where to put `npm` desktop files, as they officially recommend that all users use a local prefix, but for some reason this is not default, and most users probably don't know that they are supposed to change it.

What I'm getting at is, if we installed a `plaidchat.desktop` file locally like Google Chrome does, we could simply have a static file, no need for a template or generating anything.  But I don't know if this works for when people have their `npm` prefix set to the default system-level one.  If someone can verify that it does, this will be easy.

**Comment by rosshadden** [comment]
@GrayedFox I'm not sure what's up.  Here's the `plaidchat.desktop` I had made:

```
[Desktop Entry]
Name=Plaidchat
Exec=plaidchat
Type=Application
```

It's much more minimal than yours, but I use Arch Linux and don't have the need for anything more fancy.  Regardless, you can give it a try and if it works maybe find what's wrong with yours.

**Comment by twolfson** [comment]
I use an `alacarte` generated `.desktop` in `~/.local/share/applications/` via Cinnamon's menu editor:

```
[Desktop Entry]
Comment=plaidchat
Terminal=false
Name=Slack
Exec=plaidchat --minimize-to-tray
Type=Application
Icon=gnome-panel-launcher
```

@GrayedFox One thing that is definitely odd is passing a `%u` to the exec; this is used for passing in a URL but I have no idea where that would come from/`plaidchat` doesn't expect a URL as a parameter:

http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by GrayedFox** [comment]
I just edited down my launcher - still the same issues (although removing the %u tag was a good idea, thanks). I think this is a separate issue, which I have reported here: #103
