### ISSUE TITLE
Cannot sign into team, also not asked to sign into team

### ISSUE THREAD

**Issue by GrayedFox** [plaidchat/plaidchat#103]
Hey guys,

I just installed plaidchat over the top of the old slack-for-linux (by mistake). Ran into problems, cleared npm cache, uninstalled slack-for-linux and plaidchat, re-installed plaidchat (globally).

Any how... when I open plaidchat I am asked to sign in - however I am never asked for my team domain (so I am wondering where it comes from?).

This error is thrown repeatedly:  

```
/usr/lib/node_modules/plaidchat/app/components/slack-window.js:139 Teams not loaded yet for "https://login.slack.com/". Waiting 100ms
```

**Comment by GrayedFox** [comment]
Edit: this happens whether I open plaidchat via terminal, or via the launcher icon.

**Comment by twolfson** [comment]
To make sure we are on the same page, can you confirm the following steps are occurring to you:

1. Plaidchat is launching
2. Plaidchat prompts you with Slack's login page
3. You enter your correct credentials
4. Upon successful login, you see a blank screen

If that is the case, are there any errors in the JS console? (open via `Ctrl+Shift+I`)

Side note: While all the current collaborators are male, I would prefer to keep plural pronouns gender neutral (e.g. "guys"). In the future, please try this list of alternatives: https://twitter.com/boennemann/status/610613306693320704

**Comment by GrayedFox** [comment]
Hey, sorry for the confusion. 

1) Plaidchat launches. 
2) Enter the correct credentials
3) No successful login. The login error 'Sorry, we can't find an account with that email address' is thrown - however this is a false error. Can log in with those credentials online.
4) The error from the original post is what is shown in the developer console - namely: 
```
/usr/lib/node_modules/plaidchat/app/components/slack-window.js:139 Teams not loaded yet for 
"https://login.slack.com/". Waiting 100ms
```
Is thrown every 100ms (so it quickly gets to over 500). 

I thought it strange that the app doesn't ask for the team? How does it know which team to sign me into? (I have multiple teams with that one account - same email, different passwords, but nonetheless it feels odd and the error suggests the app is having trouble finding the team).

**Comment by twolfson** [comment]
Ah, it looks like Slack changed their login URL. Originally, Slack reserved https://login.slack.com/ as a login page. However, now that seems to be owned by a specific team. The new URL is:

https://slack.com/signin

Unfortunately, I am on a work computer at the moment and won't be able to cut a new release to repair this. I will consider high priority though so it should be patched within 48 hours.

**Comment by twolfson** [comment]
@GrayedFox We have patched the issue in `2.6.1`. Please upgrade to the latest version to verify the fix worked:

```bash
npm install -g plaidchat@latest
```

**Comment by GrayedFox** [comment]
Hi, unfortunately the issue is not yet fixed. I have plaidchat 2.6.1 installed after running npm install plaidchat@latest and receive the exact same error?

**Comment by twolfson** [comment]
We might have cached your last URL as `login.slack.url` which is now causing issues. Please try clearing the `plaidchat` config and re-running `plaidchat`:

```bash
rm -r ~/.config/plaidchat/
plaidchat
```

**Comment by GrayedFox** [comment]
Haha.... ahhhhh. So, ``` rm -rf ~/.config/plaidchat/ ``` did not work.

But ```rm -rf ~/.config/slack-for-linux/ ``` did!

Turns out it was a slack-for-linux relic. I also noticed as soon as I'd removed those config files, I was asked for my team domain again.

Cheers guys

**Comment by twolfson** [comment]
Woot, glad to hear we got a fix =D
