### ISSUE TITLE
Set "urgent" on window

### ISSUE THREAD

**Issue by rosshadden** [plaidchat/plaidchat#106]
Is it within the realm of possibilities to set "urgent" on the window?  Most window managers handle this in a convenient way, so it would be another great addition to this already great project.

**Comment by twolfson** [comment]
I am not sure what "urgent" means. Can you elaborate further on this?

I am guessing `window.requestAttention` should satisfy this but would like to verify

https://github.com/nwjs/nw.js/wiki/Window#windowrequestattentionboolean-attention

**Comment by rosshadden** [comment]
It's an Xorg window hint.  I can't find an official spec or anything, but [here's something from the GNOME docs](https://developer.gnome.org/wm-spec/#URGENCY).  I'm sure there is a more thorough explanation somewhere, since most/all modern window managers and terminals implement it.

**Comment by twolfson** [comment]
Ah, k. A quick search in `nw.js` turns up nothing =/

https://github.com/nwjs/nw.js/search?utf8=%E2%9C%93&q=WM_HINTS

However, we should play around with `window.requestAttention` to see if it gives you the desired behavior. What would you expect to see in your OS when "urgent" is set?

**Comment by rosshadden** [comment]
I don't know what happens in other window managers, but I use `i3` and in that you can specify background/foreground colors to apply to urgent tags.  So if I have Pidgin opened in tag `10` and somebody IMs me, it turns that tag the color I have specified.  Makes it easy to see what needs attention.  Maybe `window.requestAttention` does this.  I can test if you want.

**Comment by twolfson** [comment]
That would be great if you could try it out =)

**Comment by rosshadden** [comment]
`Window.requestAttention` did not do what I was hoping it would.  I do think this project should call that, as I believe it adds a badge count in Unity, Cinnamon, OSX, and Windows, but it unfortunately does not set `WM_HINTS`.

**Comment by twolfson** [comment]
Ah, that is a shame. What do you mean by "adds a badge count"? Can you provide a screenshot?

Maybe we can file an issue for X11 support of setting `WM_HINTS` on `nw.js`? There are some OS X only features that exist in `nw.js` already (e.g. https://github.com/nwjs/nw.js/wiki/Tray#trayiconsaretemplates)

**Comment by rosshadden** [comment]
Maybe. I do think that sounds like the best course of action. I'll create an issue when I get to work today. 

Also I cannot provide a screenshot because I do not use one of those window managers, but you should try opening up the dev tools in plaidchat and running requestAttention to see if it does anything in your system.

**Comment by twolfson** [comment]
I just tried it out on Cinnamon but nothing seems to be happening =/

```js
setTimeout(function () { gui.Window.get().requestAttention(true); console.log('done'); }, 5000);
```

I am still curious if there is an urgent state for Cinnamon but `wmctrl` doesn't seem to have "urgent" as a possible property =(

```
# From `man wmctrl`
       -b  ( add | remove | toggle),prop1 [,prop2 ]
              Add, remove, or toggle up to two window properties simultaneously. The window  that  is
              being  modified  must be identified with a -r action. The property change is achived by
              using the EWMH _NET_WM_STATE request. The  supported  property  names  (for  prop1  and
              prop2)   are  modal,  sticky,  maximized_vert,  maximized_horz,  shaded,  skip_taskbar,
              skip_pager, hidden, fullscreen, above and below.  Two properties are supported to allow
              operations  like maximizing a window to full screen mode. Note that this action is made
              up of exactly two shell command line arguments.
```
