### ISSUE TITLE
Unable to Select Text

### ISSUE THREAD

**Issue by mpalermo73** [plaidchat/plaidchat#107]
Hey!

I am unable to drag select text in both the messages stream and the message entry field.  Double clicking will select a word, and triple clicking will indeed select all text, but, I can't drag select.

KDE 4.13.3
X Server 1.16.0
npm 1.3.10

M.

**Comment by twolfson** [comment]
It looks like I am able to drag and select text on Linux Mint 17.1 Cinnamon =/

I have a feeling this is an issue with `nw.js`. Can you download `nw.js@0.12.2` and try selecting some text in the default screen?

```bash
# Download nw.js@0.12.2
wget http://dl.nwjs.io/v0.12.2/nwjs-v0.12.2-linux-x64.tar.gz

# Extract nw.js@0.12.2
tar xvf nwjs-v0.12.2-linux-x64.tar.gz

# Run the default nw.js screen
cd nwjs-v0.12.2-linux-x64/
nw

# An nw.js window should open with NW.JS as a prompt
# Try selecting text in the window
```

**Comment by mpalermo73** [comment]
Hey!

I did as requested and I still cannot drag select text.  double and triple
clicking still works, though.

nw.js v0.12.2
io.js v1.2.0
Chromium 41.0.2272.76
commit hash: caedb6a-296de67-be948af-459755a-2bdc251-1764a45


M.

**Comment by twolfson** [comment]
It sounds like this is a problem between your OS and nw.js. Can you please open an issue on nw.js?

https://github.com/nwjs/nw.js

**Comment by mpalermo73** [comment]
I VERY sorry for the delay.  I have opened an issue there and referenced this thread.

https://github.com/nwjs/nw.js/issues/3663


M.
