### ISSUE TITLE
Start a mailing list

### ISSUE THREAD

**Issue by twolfson** [plaidchat/plaidchat#111]
We have releases frequently enough that we should start a mailing list to let people know about new updates. I have seen a few options:

- Google Groups
- Mailchimp (or similar newsletter service)

To subscribe, we could prob include a link/badge in the README. Thoughts?

/cc @wlaurance

**Comment by wlaurance** [comment]
I'm thinking a Mailchimp account will work well. We can add a signup button in the README.

Content for the newsletter can be gathered from the Changelog and issues.

**Comment by twolfson** [comment]
Cool. We should prob get our logo situation sorted out soon so we can brand the email properly. Can you take a look at #61?

**Comment by twolfson** [comment]
Alright, I have set up a Mailchimp account. I am a bit hesitant with this due to my address being sent out on every email (thanks spam laws).

I sent you an invite to `will+plaidchat@dubsoft.net`. I am using the altered email variation to prevent security issues between your main account and plaidchat specific account (if you will ever want one). For that matter, I suggest using `{{username}}plaidchat` as the username as well.

**Comment by twolfson** [comment]
This has been completed in `2.12.0`
