### ISSUE TITLE
Switching teams via shortcut (Ctrl + K) does not change current team indicator in left panel

### ISSUE THREAD

**Issue by allanbreyes** [plaidchat/plaidchat#116]
Moved to the first team via quick switcher, but second team still shows indicator.

![image](https://cloud.githubusercontent.com/assets/7947900/8845280/31645e2a-30e3-11e5-9847-4d4832d4881f.png)

Low priority, for sure, but thought I'd submit it just for documentation.

**Comment by twolfson** [comment]
I am not sure what quick switcher you are referring to. Can you please provide instructions on how to reproduce?

**Comment by allanbreyes** [comment]
Quick switcher is located on the bottom left, accessible via `Ctrl/Cmd + K` or by hovering over it:

![image](https://cloud.githubusercontent.com/assets/7947900/8857945/53d00e76-313a-11e5-9238-c66eecd3bb40.png)

I'm running:
- Ubuntu 15.04
- Node v0.12.4

I think the issue is actually a functional one, now, rather than just aesthetic.  After switching, it actually replaces the currently selected team to get remapped to that switched-to team, but the icon picture remains the same.

I'm able to remap all the teams now to the one I switched to:

![image](https://cloud.githubusercontent.com/assets/7947900/8858073/080760d8-313b-11e5-9b58-576fdc9687ac.png)

![image](https://cloud.githubusercontent.com/assets/7947900/8858080/11eecdc0-313b-11e5-933d-fb3afe265245.png)

![image](https://cloud.githubusercontent.com/assets/7947900/8858096/1f7b1782-313b-11e5-8325-c1836d4f9177.png)

![image](https://cloud.githubusercontent.com/assets/7947900/8858105/272b439e-313b-11e5-99a0-706b27ecdb14.png)

(Notice how all 4 teams are now pointing to `rubyonrails`)

**Comment by twolfson** [comment]
I guess I never realized that you can switch between teams via that Quick Switcher. When working, I typically only have 1 team open.

With respect to solving the issue, we will have to research the JS mechanism to see how the Quick Switcher actually performs the switch. Hopefully it isn't too bad and we can proxy it. Otherwise, we might have to dig into the Windows/OSX code to see how they bind to the application.

For an ETA, I would say by the end of next weekend (not this one). However, anyone else who wants to can call out that they are grabbing this. I will write a comment when I begin working on it.

**Comment by twolfson** [comment]
Oh, and thank you for the bug report =)

**Comment by twolfson** [comment]
Notes for self and/or person who solves this. I found 2 solution paths (there are prob even more):

- Overwrite `TS.ui.omnibox.selectTeamResult` (quick switcher's team select behavior)
- Replace all current override hacks with integration on top of `TSSSB.call` (more work but literally makes us 1:1 Windows/OS X clients as this is how they operate)

**Comment by twolfson** [comment]
I am going to try implementing a patch by overriding `TS.ui.omnibox.selectTeamResult`. Then, after that's all said and done, I think we should move to actually implementing `TSSSB` as it reduces the size of our hacks significantly and makes us super consistent with other clients.

**Comment by twolfson** [comment]
A patch is now up in https://github.com/plaidchat/plaidchat/pull/120 =)

**Comment by allanbreyes** [comment]
Awesome!  Thanks, @twolfson.  I'll close this.
