### ISSUE TITLE
Custom organization sort (with drag and drop maybe?)

### ISSUE THREAD

**Issue by naps62** [plaidchat/plaidchat#124]
I don't know how the official Slack app handles this (or if it handles it at all), since I only use Linux, but I'd love the ability to sort my organizations using a custom order.

I noticed this was already mentioned [here](https://github.com/plaidchat/plaidchat/issues/87) but I thought it belonged to an issue of it's own

I'd like to implement this myself, but I currently have no experience with React or Flux, so I guess it'll take some time. Plus, these are busy times at my company :smile:

**Comment by twolfson** [comment]
I think there would be 2 parts (i.e. 2 separate PRs) to solving this problem:

1. Add preservation of team information between application sessions (e.g. keep track of the teams, their icons, and their orders)
    - This would get teams to always be loaded in the same order
2. Add support for drag/drop of team icons (upon drag/drop of team icon, update team ordering and preserve with application state)
    - This adds customized order which persists on future loads

Let me know if you run into any issues =)
