### ISSUE TITLE
Detect user activity via inputs or desktop [un]locking

### ISSUE THREAD

**Issue by ofavre** [plaidchat/plaidchat#126]
As a desktop application, the application has access to more hints of the user presence.
An auto-away (and auto-online) based on mouse and keyboard activity is a must have.
And similarly with the locking and unlocking of the desktop.

I currently cannot find any client that implements this, be the first!

**Comment by twolfson** [comment]
I think this seems like a fair request. Although, I am pretty sure most people would hate to see anything watching mouse/keyboard monitoring so we should find a less intrusive way to do that.

For the first revision, I suggest we don't allow customization of timings (e.g. fix to 5 minutes of inactivity -> away) but then support it later on.
