### ISSUE TITLE
Slack Linux beta sign up list is up

### ISSUE THREAD

**Issue by twolfson** [plaidchat/plaidchat#128]
As a heads up, Slack is opening up a beta list for their Linux client.

https://twitter.com/SlackHQ/status/628701873701126144

I plan to help maintain `plaidchat` until a public beta is open. After that point, I have no idea what will happen.

Does anyone think that it would be a nice gesture to post a link to Slack's beta sign up page?

**Comment by twolfson** [comment]
I got my beta invite today. There are already a lot of features that we wanted in `plaidchat` that exist in the beta client (e.g. team shortcuts, context menu, `.desktop` integration).

It seems to be written on top of electron (I see some `atom` mentions in the binary file).

Noticable differences:

- Tray icon is monochrome slack (similar to Windows)
- Tray icon notifications either exist or don't exist (similar to Windows)
- Team sidebar uses initials for team avatar defaults

![selection_156](https://cloud.githubusercontent.com/assets/902488/9103766/ce5dca92-3bc7-11e5-949e-e3e3477810bd.png)

![selection_158](https://cloud.githubusercontent.com/assets/902488/9103792/ebd64ef0-3bc7-11e5-8766-3fa416d3277f.png)

![selection_159](https://cloud.githubusercontent.com/assets/902488/9103794/02a19c20-3bc8-11e5-9c31-4d8ab3c889c5.png)

**Comment by SomeKittens** [comment]
They won't be dogfooding the app ( https://twitter.com/SlackHQ/status/628703795791446016 ) so I'd prefer something made by people who actually use it.

**Comment by twolfson** [comment]
@SomeKittens It's not clear that they aren't dogfooding from that post. The response was a joke in response to a sarcastic joke (hence the wink).

With respect to `plaidchat`, I should make it clear that we built this more out of necessity than to spite Slack. As proof, here is the "Why" section in our `1.0.0` version.

https://github.com/plaidchat/plaidchat/tree/v1.0.0#why

The client offered by Slack has a lot more features (better team switching, integrated menus) and better integration since they weren't hacking over existing JS/HTML. I should also point out that Slack's desktop apps seem to share the same code base -- an Electron application with different one-offs for each platform.

If you are interested in digging through the code base, it can be done by extracting the archive at ` /usr/share/slack/resources/app.asar` (ignore `app.asar.extracted`). This can be found once you have installed the `.deb` provided by Slack. An extraction client can be found here:

https://www.npmjs.com/package/asar

**Comment by davewongillies** [comment]
The beta is now available on https://slack.com/apps
