### ISSUE TITLE
Hide menu

### ISSUE THREAD

**Issue by ghost** [plaidchat/plaidchat#130]
Hi!

This program is awesome. One nitpick: I would like to be able to hide the menu bar. In the screenshot on the webpage it does not show a menu bar (probably you are running Ubuntu?) but on my Xmonad based setup it does and I don't need it :)

Thanks!

**Comment by jbo-ableton** [comment]
(If it's not possible to do already, I might try making a patch myself :)

**Comment by twolfson** [comment]
Ah, we never updated the screenshot after the addition of the menu bar =/

I am open to supporting this. I don't believe we can "hide" the menu bar but we can not add it (if someone provides a CLI) option. 

https://github.com/nwjs/nw.js/wiki/Window#windowmenu

However, currently we are leveraging nw.js' ability to integrate shortcuts for the entire window via these means.

https://github.com/nwjs/nw.js/wiki/MenuItem#menuitemkey

As a result, we should probably take care of this in 2 steps:

1. Move all menu shortcuts to shortcuts
    - https://github.com/nwjs/nw.js/wiki/MenuItem#menuitemkey
2. Add either CLI option to never show menu or build a toggle menu shortcut + menu item
