### ISSUE TITLE
Super tiny on a 3200x1800 screen

### ISSUE THREAD

**Issue by Movarrin** [plaidchat/plaidchat#131]
Whenever I start the client, the text loads super tiny. I can increase the font size to make it usable but that seems to really take a great deal of resources. After about 15 seconds the client recovers and is usable.
I'm losing the resolution in the images. I've tried to include elements that can give you an idea the issue.
If you look at how large the menu bar title bar, you can infer how much I had to increase font size to read the chat text. On my screen the font appears as if it set to 4pt.

![selection_023](https://cloud.githubusercontent.com/assets/12075077/9473068/c552418a-4b26-11e5-9f0b-119fd9b5e494.jpg)

![selection_024](https://cloud.githubusercontent.com/assets/12075077/9473107/1096b36a-4b27-11e5-98bf-b8e94332c0b6.jpg)

second pic is the app maximized.

**Comment by twolfson** [comment]
This sounds like the same problem from #118 (mostly documentation PR). I think that PR is still open since we are looking for something better than requiring an extra CLI option.

Can you try running `plaidchat` with the following CLI flag:

```bash
plaidchat --force-device-scale-factor=2
```

**Comment by Movarrin** [comment]
that did result in readable text in a maximized window without input from me. So that's good. The problem is now the menu bar is farking huge. LOL.

I should mention I'm already using a scaling set to 2 because this is far from the only app with an issue like this. At least, after blowing up yours is very usable and the icons enlarge with it.

I can definitely use it like this until a more elegant solution is found.

**Comment by Movarrin** [comment]
Also now I HAVE to use it maximized or all I can see is this.
![screenshot from 2015-08-25 13 00 45](https://cloud.githubusercontent.com/assets/12075077/9473555/641d2eea-4b29-11e5-9dcf-7fcec73b60e3.png)

**Comment by Movarrin** [comment]
If you feel it's a repeat of another issue please feel free to merge or close this.

**Comment by twolfson** [comment]
Yep, sounds like the same problem as #118. Closing this issue as a duplicate
