### ISSUE TITLE
Problems while fetching data from a channel

### ISSUE THREAD

**Issue by copyme** [plaidchat/plaidchat#133]
I came back to Plaidchat after a while and unfortunately it does not work quite well as before. Right now after I logged in and I've tried to access a channel I got a message about reconnecting to it and after some time this:

Apologies, we're having some trouble with your web socket connection. We tried falling back to Flash, but it appears you do not have a version of Flash installed that we can use.

But we've seen this problem clear up with a restart of your browser, a solution which we suggest to you now only with great regret and self loathing.

**Comment by twolfson** [comment]
Sorry for the slow reply. Can you provide a screenshot of what you are seeing?

**Comment by copyme** [comment]
@twolfson Here you go: 
![plaidchat](https://cloud.githubusercontent.com/assets/456607/9808808/fbde0a56-5862-11e5-8c6f-a5c62dfbb2d5.png)

BTW In my network I need to proxy. Does plaidchat use system settings? Maybe this is related.

**Comment by twolfson** [comment]
That sounds like the likely suspect. `plaidchat` should be using system settings. Is everything configured system wide to use the proxy server?

**Comment by twolfson** [comment]
Judging by how HTTP/HTTPS is working, I am guessing yes it's properly configured but something is awry with websocket ports/proxies. Can you try using the Slack web client in Chrome and see if you encounter the same issue?

https://my.slack.com/

**Comment by copyme** [comment]
@twolfson I've checked in chromium and it does not work -- same problem.

**Comment by twolfson** [comment]
Under the hood, we use `nw.js` which is a Chromium based browser implementation. It sounds like the problem resides with the proxy and how it interacts with websockets. Have you set up anything special in Firefox that allows it to work?

**Comment by copyme** [comment]
@twolfson In Firefox I had to setup proxy settings -- Firefox does not use the system ones. On the other hand chromium does use system settings, which in my case are also setup correctly -- other applications works without any problems.

**Comment by copyme** [comment]
@twolfson I solved the problem. I've configured the proxy settings via KDE tools. Right now I turned them off and configured proxy via YaST in openSUSE. After, that it works. From the network test provided by slack.com it seems that problem was related to web socks. So I guess KDE tools are not doing all the job well.

**Comment by twolfson** [comment]
Alright, glad to hear everything worked out =)
