### ISSUE TITLE
Fails to install on Linux Mint 17.1

### ISSUE THREAD

**Issue by jtresponse** [plaidchat/plaidchat#140]
I've installed Node.js and npm with apt-get.

If I run  npm install plaidchat -g I get errors in the output:
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/john/npm-debug.log
npm ERR! not ok code 0

However, /home/john/npm-debug.log does not exist !

Any clues ?

**Comment by twolfson** [comment]
Typically the node installed via apt is out of date. Please install node via the steps here: 

https://github.com/nodesource/distributions

**Comment by jtresponse** [comment]
Thanks.
I found the following worked for me:
http://developwithguru.com/how-to-install-node-js-and-npm-in-ubuntu-or-mint/

However, that seems a bit unstable as well, as I had a number of version mismatch warnings.
I think I might have chosen a platform a bit more stable then Node.js to build with.

**Comment by twolfson** [comment]
`chris-lea/nodejs` is what the distro scripts use.

https://github.com/nodesource/distributions/blob/b970817abc336a16647a53b6dba13c1be83a6b12/deb/setup#L120-L125

However, you should only only need to `apt-get install node` -- `npm` should come freely.

```bash
# Remove existing node/npm installs
sudo apt-get remove nodejs nodejs-dev npm

# Add the repository via `apt` and update references
sudo sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update

# Install node only (npm will be picked up automatically)
sudo apt-get install nodejs

# Verify `node` and `npm` versions
node --version
npm --version
```

**Comment by twolfson** [comment]
Closing this issue as it seems to be resolved.
