### ISSUE TITLE
Plaidchat installation via npm leaves extraneous files?

### ISSUE THREAD

**Issue by GrayedFox** [plaidchat/plaidchat#141]
I'm not 100% sure this is actually a plaidchat error, although it is strange that no other globally installed package reports this error. I use two aliases in order to quickly list installed packages. 

The first is *npmpkgs* which runs this (local): ```npm list --depth=0```
The second is *npmgpkgs* which runs this ```npm list -g --depth=0```

I've been battling NPM and nodejs all day, hence me being unsure it is actually plaidchat, but I thought I'd start here. Strangely, when listing globally installed packages, I get this in the console:

```
npm ERR! extraneous: buffer-to-vinyl /usr/lib/node_modules/plaidchat/node_modules/buffer-to-vinyl
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/buffer-to-vinyl: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/buffer-to-vinyl/package.json'
npm ERR! extraneous: decompress-unzip /usr/lib/node_modules/plaidchat/node_modules/decompress-unzip
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/decompress-unzip: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/decompress-unzip/package.json'
npm ERR! extraneous: download /usr/lib/node_modules/plaidchat/node_modules/download
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/download: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/download/package.json'
npm ERR! extraneous: download-status /usr/lib/node_modules/plaidchat/node_modules/download-status
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/download-status: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/download-status/package.json'
npm ERR! extraneous: duplexify /usr/lib/node_modules/plaidchat/node_modules/duplexify
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/duplexify: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/duplexify/package.json'
npm ERR! extraneous: meow /usr/lib/node_modules/plaidchat/node_modules/meow
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/meow: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/meow/package.json'
npm ERR! extraneous: merge-stream /usr/lib/node_modules/plaidchat/node_modules/merge-stream
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/merge-stream: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/merge-stream/package.json'
npm ERR! extraneous: read-all-stream /usr/lib/node_modules/plaidchat/node_modules/read-all-stream
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/read-all-stream: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/read-all-stream/package.json'
npm ERR! extraneous: vinyl-fs /usr/lib/node_modules/plaidchat/node_modules/vinyl-fs
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/vinyl-fs: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/vinyl-fs/package.json'
```

This is really weird... I tried pruning, but that doesn't work (and it shouldn't, since there is no package.json in my home directory, because why would I need one for globally installed packages).

I don't know if NPM is reporting a false positive, or if something more sinister is at hand. Have already cleared NPM cache (global and local) and still get this in response.

**Comment by twolfson** [comment]
I'm a bit confused as to what you are looking for. Can you explain what you are trying to accomplish?

**Comment by GrayedFox** [comment]
Hey twolfson, 

I'm actually trying to make sure that Plaidchat has not installed with a bunch of leftover dependencies (like dev dependecies), and if so, how would I go about removing them? I have tried navigating to to where plaidchat is installed and running ```npm prune``` but this didn't work!

**Comment by twolfson** [comment]
`devDependencies` should never be installed via `npm install` when a package name is specified (e.g. `npm install plaidchat`) unless you have overriden a `npm config`:

https://docs.npmjs.com/misc/config#dev

That being said to use `npm prune`, you would need to use it as if you were performing development on that repo. For this scenario, it should work if you go to the `plaidchat` directory and run `npm prune` there:

```bash
cd /usr/lib/node_modules/plaidchat/
npm prune
```

**Comment by GrayedFox** [comment]
I tried ```npm prune``` in the ```/usr/lib/node_modules/plaidchat``` directory - to no avail.

After some further investigation and closer inspection of the output log, I have a feeling this is actually related to how I've installed NPM/Node. Is it possible NPM is traversing too far down the directory tree from my own project directory and seeing the node_modules folder in /usr/lib and for some reason listing dependencies of plaidchat, perhaps?

That might explain why it lists files as missing, but related files as also extraneous. Full log posted below. Not sure why it's only Plaidchat dependencies popping up and not other packages :confused: 

/usr/lib
├── babel@5.8.23
├── backbone@1.2.3
├── eslint@1.6.0
├── hub@2.0.1
├── jscs@2.3.2
├── npm@3.3.8
├── plaidchat@2.15.0
├── selenium-webdriver@2.47.0
└── underscore@1.8.3

npm ERR! extraneous: buffer-to-vinyl /usr/lib/node_modules/plaidchat/node_modules/buffer-to-vinyl
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/buffer-to-vinyl: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/buffer-to-vinyl/package.json'
npm ERR! extraneous: decompress-unzip /usr/lib/node_modules/plaidchat/node_modules/decompress-unzip
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/decompress-unzip: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/decompress-unzip/package.json'
npm ERR! extraneous: download /usr/lib/node_modules/plaidchat/node_modules/download
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/download: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/download/package.json'
npm ERR! extraneous: download-status /usr/lib/node_modules/plaidchat/node_modules/download-status
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/download-status: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/download-status/package.json'
npm ERR! extraneous: duplexify /usr/lib/node_modules/plaidchat/node_modules/duplexify
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/duplexify: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/duplexify/package.json'
npm ERR! extraneous: meow /usr/lib/node_modules/plaidchat/node_modules/meow
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/meow: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/meow/package.json'
npm ERR! extraneous: merge-stream /usr/lib/node_modules/plaidchat/node_modules/merge-stream
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/merge-stream: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/merge-stream/package.json'
npm ERR! extraneous: read-all-stream /usr/lib/node_modules/plaidchat/node_modules/read-all-stream
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/read-all-stream: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/read-all-stream/package.json'
npm ERR! extraneous: vinyl-fs /usr/lib/node_modules/plaidchat/node_modules/vinyl-fs
npm ERR! error in /usr/lib/node_modules/plaidchat/node_modules/vinyl-fs: ENOENT, open '/usr/lib/node_modules/plaidchat/node_modules/vinyl-fs/package.json'
npm ERR! missing: through2@~0.5.1, required by stream-combiner2@1.0.2
npm ERR! missing: meow@^3.1.0, required by pretty-bytes@1.0.4
npm ERR! missing: single-line-log@~0.3.1, required by progress-stream@1.1.1
npm ERR! missing: through2@~0.2.3, required by progress-stream@1.1.1
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: async@0.9.0, required by extract-zip@1.1.1
npm ERR! missing: concat-stream@1.5.0, required by extract-zip@1.1.1
npm ERR! missing: debug@0.7.4, required by extract-zip@1.1.1
npm ERR! missing: mkdirp@0.5.0, required by extract-zip@1.1.1
npm ERR! missing: object-assign@^2.0.0, required by decompress-tar@3.1.0
npm ERR! missing: through2@^0.6.1, required by decompress-tar@3.1.0
npm ERR! missing: vinyl@^0.4.3, required by decompress-tar@3.1.0
npm ERR! missing: readable-stream@^2.0.0, required by tar-stream@1.2.2
npm ERR! missing: object-assign@^2.0.0, required by decompress-tarbz2@3.1.0
npm ERR! missing: through2@^0.6.1, required by decompress-tarbz2@3.1.0
npm ERR! missing: vinyl@^0.4.3, required by decompress-tarbz2@3.1.0
npm ERR! missing: commander@~2.8.1, required by seek-bzip@1.0.5
npm ERR! missing: object-assign@^2.0.0, required by decompress-targz@3.1.0
npm ERR! missing: through2@^0.6.1, required by decompress-targz@3.1.0
npm ERR! missing: vinyl@^0.4.3, required by decompress-targz@3.1.0
npm ERR! missing: readable-stream@^2.0.2, required by buffer-to-vinyl@1.0.1
npm ERR! missing: readable-stream@^2.0.0, required by read-all-stream@3.0.1
npm ERR! missing: readable-stream@~2.0.0, required by through2@2.0.0
npm ERR! missing: object-assign@^4.0.1, required by meow@3.4.2
npm ERR! missing: path-exists@^2.0.0, required by find-up@1.0.0
npm ERR! missing: graceful-fs@^3.0.0, required by vinyl-fs@1.0.0
npm ERR! missing: object-assign@^2.0.0, required by vinyl-fs@1.0.0
npm ERR! missing: strip-bom@^1.0.0, required by vinyl-fs@1.0.0
npm ERR! missing: through2@^0.6.1, required by vinyl-fs@1.0.0
npm ERR! missing: vinyl@^0.4.0, required by vinyl-fs@1.0.0
npm ERR! missing: readable-stream@>=1.0.33-1 <1.1.0-0, required by through2@0.6.5
npm ERR! missing: through2@~2.0.0, required by through2-filter@2.0.0
npm ERR! missing: glob@~3.1.21, required by globule@0.1.0
npm ERR! missing: minimatch@~0.2.11, required by globule@0.1.0
npm ERR! missing: end-of-stream@1.0.0, required by duplexify@3.4.2
npm ERR! missing: readable-stream@^2.0.0, required by duplexify@3.4.2
npm ERR! missing: through2@^0.6.1, required by merge-stream@0.1.8
npm ERR! missing: object-assign@^4.0.1, required by vinyl-assign@1.2.1
npm ERR! missing: readable-stream@^2.0.0, required by vinyl-assign@1.2.1
npm ERR! missing: decompress-targz@^2.0.1, required by download@3.3.0
npm ERR! missing: decompress-unzip@^2.0.0, required by download@3.3.0
npm ERR! missing: get-stdin@^3.0.0, required by download@3.3.0
npm ERR! missing: meow@^2.0.0, required by download@3.3.0
npm ERR! missing: through2@^0.6.1, required by download@3.3.0
npm ERR! missing: vinyl@^0.4.3, required by download@3.3.0
npm ERR! missing: vinyl-fs@^0.3.7, required by download@3.3.0
npm ERR! missing: strip-dirs@^0.1.1, required by decompress-tar@2.0.2
npm ERR! missing: through2@^0.6.1, required by decompress-tar@2.0.2
npm ERR! missing: vinyl@^0.4.3, required by decompress-tar@2.0.2
npm ERR! missing: readable-stream@~1.0.26, required by bl@0.9.4
npm ERR! missing: strip-dirs@^0.1.1, required by decompress-tarbz2@2.0.2
npm ERR! missing: tar-stream@^0.4.5, required by decompress-tarbz2@2.0.2
npm ERR! missing: through2@^0.6.1, required by decompress-tarbz2@2.0.2
npm ERR! missing: vinyl@^0.4.3, required by decompress-tarbz2@2.0.2
npm ERR! missing: chalk@^0.5.1, required by download-status@2.2.1
npm ERR! missing: object-assign@^2.0.0, required by download-status@2.2.1
npm ERR! missing: meow@^3.3.0, required by lpad-align@1.1.0
npm ERR! missing: minimist@~0.0.7, required by rc@0.5.5
npm ERR! missing: readable-stream@~2.0.0, required by bl@1.0.0
npm ERR! missing: glob@^5.0.14, required by rimraf@2.4.3
npm ERR! missing: wordwrap@0.0.2, required by cliui@2.1.0
npm ERR! missing: esprima-fb@13001.1001.0-dev-harmony-fb, required by jstransform@10.1.0
npm ERR! missing: source-map@0.1.31, required by jstransform@10.1.0

**Comment by GrayedFox** [comment]
Well that's weird.

I uninstalled plaidchat completely and cleared my cache, and then reinstalled plaidchat globally - and viola! No more error reports when listing globally installed packages.

This is just a hunch - but I think I accidentally installed plaidchat (globally) while I happened to be in my local project directory. This may have caused some strange associations not present before - whatever the case, if anyone else has the problem, I recommend uninstalling plaidchat, clearing your cache, and making sure you are in your $HOME directory before reinstalling plaidchat globally.

Closing this as it's resolved :+1:

**Comment by twolfson** [comment]
Ah, interesting. On a similar note, now that you mention it -- that would match the behavior of `npm link` which sets up `plaidchat` from a local directory to your global. As a result, it would expect `devDependencies` to be installed as well.

Anyway, thanks for the info and glad it's all fixed =)

**Comment by mmclau14** [comment]
it looks like this was fixed?
when i do 
```
sudo npm -g update
```
on node v7.0.0 it no longer shows me extra modules
