### ISSUE TITLE
mark as read when is opened

### ISSUE THREAD

**Issue by Mte90** [plaidchat/plaidchat#144]
I work with a multimonitor system and I leave slack in a monitor but when there is something in chat is required an action with the mouse to mark as read the message.
Is possible add an option for that?

**Comment by twolfson** [comment]
Slack provides keyboard shortcuts for marking messages as read, here's a tweet about them:

https://twitter.com/slackhq/status/473947505827119105

That screen can be accessed via the team dropdown and selecting "Preferences".

**Comment by Mte90** [comment]
Ok but is not the feature that i want. In this way I can only change the behaviour of marking as read the message with the scrolling.
I want only when I have the window opened in channel opened not alert to me new message and mark as read but only in that channel.

**Comment by twolfson** [comment]
Ah, sorry. I misinterpretted your request as a keyboard shortcut request. While I think it's possible, I don't think it's a feasible feature to build/maintain. The logic would look like:

- When we receive a new message
    - If window isn't visible, do nothing (prob requires talking to X11)
    - Press ESC or run some other code in Slack to mark message as read

But then there are edge cases like, what if you are AFK or marked as Away within Slack? You prob wouldn't want messages marked as read then but that would be yet another setting/feature to implement.

**Comment by Mte90** [comment]
In that case I already turn off the client so in my case is not a problem.
I can understand that is an edge cases I can work on a my solution when I have time maybe something with xdotool that trigger the click on the window :-)
