### ISSUE TITLE
On start if missing internet blank page

### ISSUE THREAD

**Issue by Mte90** [plaidchat/plaidchat#145]
On my kde5 station the internet connection start after the launch of kde and I have plaidchat in the bootup but I get a blank page because is not connected to internet in that moment.
Maybe get an alert and a timeout for retry the connection will be useful.

**Comment by twolfson** [comment]
Did some research on this, unfortunately there is no `onerror` event for an iframe failing to load =/

Slack's official client seems to listen to `online` and `offline` browser events as well as leverage `navigator.onLine`:

https://developer.mozilla.org/en-US/docs/Online_and_offline_events

```js
      if (this.onlineEvent == null) {
        this.onlineEvent = rx.DOM.fromEvent(window, 'online');
      }
      if (this.offlineEvent == null) {
        this.offlineEvent = rx.DOM.fromEvent(window, 'offline');
      }
      if (this.isOnline == null) {
        this.isOnline = (function() {
          return navigator.onLine;
        });
      }
```

But for keeping the solution simple, I propose we check `navigator.onLine`,  inform them they are offline, and give them a button to refresh the page.

**Comment by Mte90** [comment]
any news for that?

**Comment by twolfson** [comment]
I think I was waiting for feedback from others

**Comment by Mte90** [comment]
Any news for that?

**Comment by justinnichols** [comment]
I have no feedback to add.  The feature that @twolfson suggested is probably the best course of action.
