### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by hrushikesht** [plaidchat/plaidchat#146]
Does the client support proxy authentication?

**Comment by twolfson** [comment]
Currently, it should attach to system level settings. For a proxy exclusively for `plaidchat`, we currently don't support this feature.

I was hoping there would be a Chromium flag for it but it looks like there isn't:

https://github.com/nwjs/nw.js/wiki/Command-line-switches

However, we should be able to add proxy support via:

https://github.com/nwjs/nw.js/wiki/App#setproxyconfigconfig

I would imagine that we accept it as a CLI parameter. For example:

```bash
plaidchat --proxy-config "foopy:80"
```

Would you be interested in opening a PR for this?

**Comment by HrushikeshT** [comment]
I would love to but I don't know how to program about it. In fact I am an amateur in programming. Can you please tell me which resources should I use to learn this?

**Comment by twolfson** [comment]
Sure thing. We are using Commander for our CLI parsing:

http://tj.github.io/commander.js/

https://github.com/plaidchat/plaidchat/blob/v2.15.0/app/js/index.js#L22-L32

We should be able to add `--proxy-config` as with our other CLI options (e.g. `--minimize-to-tray`).

Then, we can use the same logic for detecting someone setting a `proxyConfig` option:

https://github.com/plaidchat/plaidchat/blob/v2.15.0/app/js/index.js#L159-L161

And we can talk to the `App` via `gui.App` as seen here:

https://github.com/plaidchat/plaidchat/issues/146#issuecomment-170353581

The documentation for `App.setProxyConfig` can be found here:

https://github.com/nwjs/nw.js/wiki/App#setproxyconfigconfig
