### ISSUE TITLE
running plaidchat on Scientific Linux 6.7(carbon) fails error while loading shared libraries: libnotify.so.4

### ISSUE THREAD

**Issue by AtefBN** [plaidchat/plaidchat#149]
I have been trying to use Plaidchat on SL6.7 and failing because of the lack of libnotify.so.4.
error while loading shared libraries: libnotify.so.4 cannot open shared object file: No such file or directory.

**Comment by twolfson** [comment]
Can you see if a solution similar to #1 will work?

**Comment by AtefBN** [comment]
I tried what was suggested in #1 and it worked. However this has changed the error stack to:
 ```
/usr/lib/node_modules/plaidchat/node_modules/nw/nwjs/nw: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/node_modules/plaidchat/node_modules/nw/nwjs/nw)
/usr/lib/node_modules/plaidchat/node_modules/nw/nwjs/nw: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/lib/node_modules/plaidchat/node_modules/nw/nwjs/nw)

```

Thanks for the help !

**Comment by twolfson** [comment]
That's great to hear. Were you able to resolve the new GLIBC errors?

**Comment by AtefBN** [comment]
Nope, I have on my machine glibc 2.12-1.166.el6_7.7. I am open to suggestions.

**Comment by twolfson** [comment]
It looks like `nw.js` wants a higher level of `glibc` installed so I guess try upgrading. Is there any reason you aren't using Slack's official Linux client?

**Comment by AtefBN** [comment]
Actually, I have escaped using the official linux client for slack for the Glibc error i receive on install. Seems quite helpless though.
