### ISSUE TITLE
Don't open a window with --help or --version

### ISSUE THREAD

**Issue by logological** [plaidchat/plaidchat#150]
Plaidchat supports command-line options for outputting a help screen (`-h`, `--help`) or the version number (`-V',`--version`).  When using either of these options, Plaidchat briefly opens and then closes an X11 window before printing the requested information to the console.  This seems rather unnecessary and distracting.

**Comment by twolfson** [comment]
We should be able to resolve this by sharing CLI parsing between `nw.js` and our `run.js` script. Would you be interested in writing a PR for this?

**Comment by logological** [comment]
I'm afraid I have very little knowledge of JavaScript, so I'm not really in a position to update the code and make a pull request.

**Comment by twolfson** [comment]
Unfortunately I don't have time to work on this PR either =/
