### ISSUE TITLE
Can't delete a Slack I have logged in from plaidchat menu

### ISSUE THREAD

**Issue by happy-dev** [plaidchat/plaidchat#151]
Hi, 

I would like to be able to delete a Slack I have logged in from the plaidchat menu, but can't figure out how to do it. 

I am very sorry of that is a RTFM question. I read it, I swear. 

If some code is required, I am willing to try, although I'll need some help to get started. 

All the best ! 

BTW : Great software ! I use it all the time

**Comment by twolfson** [comment]
To "delete" a team, logging out should do the trick. It's been a while since I have used Slack but if it still remembers the team on the log in screen, then there should be a way to remove the team from that as well.

**Comment by happy-dev** [comment]
Hmmm... for me it does not. Logging out does but the "logged out Slack" below in the menu, but it doesn't remove the Slack entry from the menu

**Comment by twolfson** [comment]
There is definitely a button somewhere on that login screen where Slack asks you to select a team but I am fairly out of context. Can you look some more?

**Comment by happy-dev** [comment]
Doing it :)

**Comment by happy-dev** [comment]
This is what I see. Below is the footer of the website. In the menu, only zoom in/out and developper's tool

![screenshot from 2016-07-19 17-14-27](https://cloud.githubusercontent.com/assets/9748542/16955264/49c4fdee-4dd4-11e6-8a22-707af119e0fa.png)

**Comment by twolfson** [comment]
Hmm, wierd. I tried browsing it myself and couldn't find anything. I'm sure there's something but not sure where. It definitely wouldn't be a custom integration since we use Slack's website so they would have to have a similar setup for browsers.

I'm going to re-open the issue but I don't have time to dig in further =/

**Comment by happy-dev** [comment]
Thank you for your help already. 

As far as I know, Slack's website doesn't allow multiple slack per Window, so I believe this is a custom feature of the app

**Comment by twolfson** [comment]
We are using multiple iframes to load multiple windows but we are scraping the login page/Slack application for team info ;)
