### ISSUE TITLE
Leaving project

### ISSUE THREAD

**Issue by twolfson** [plaidchat/plaidchat#154]
Hey all, I've come to the decision to leave this project as a maintainer. I haven't made any contributions in the past year, the Slack official client is superior in almost every way I can think of, and I no longer use Slack (at least for the past year).

In my opinion, we should additionally deprecate/shut down the project fully as the project itself is being neglected, has way less features, and mostly confuses those that should be using the official client.

@wlaurance What are your thoughts?

**Comment by wlaurance** [comment]
@twolfson I also haven't made any contributions. I use Slack but only on a Mac now.

The official Slack client is better and maintained.
