### ISSUE TITLE
Install slack on Kali 2.0

### ISSUE THREAD

**Issue by onthefrontline** [plaidchat/plaidchat#156]
Problem installing Slack on Kali:

root@kali:~# git clone git@github.com:wlaurance/slack-for-linux.git && cd slack-for-linux
Cloning into 'slack-for-linux'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by twolfson** [comment]
This project was renamed to `plaidchat` as well as is now shut down. Please use the Slack official client instead:

https://slack.com/downloads/linux
