### ISSUE TITLE
Add notification badges to team icons

### ISSUE THREAD

**Issue by twolfson** [plaidchat/plaidchat#39]
When multiple teams are visible in the sidebar, we should have notification badges if there are any unread messages as with other desktop clients.

![Screenshot](http://a4.mzstatic.com/us/r30/Purple3/v4/88/86/9b/88869b89-cde5-5a50-26cc-3fcd181e8806/screen800x500.jpeg)

**Comment by madmuffin1** [comment]
Is it possible to get the sidebar (don't mind the notification badges for now) in the current version already? I seem to be unable to find the switch for it.

**Comment by LuckyThirteen** [comment]
@madmuffin1 : sign in into multiple teams, then restart the app, the sidebar should appear after that.

**Comment by madmuffin1** [comment]
@LuckyThirteen :+1: thanks, I was expecting it to pop up right away!

**Comment by twolfson** [comment]
Yep, currently only visible after restart. There is no internal state in the application which lead to this problem. We are looking to resolve it in #38.

**Comment by skeet70** [comment]
+1 on this enhancement. Was really confused when _almost_ everything worked just like my co-workers official Slack client, but this didn't. The Notification Badge (PM or mention) and the small grey blob (unread activity) would both be great.

**Comment by twolfson** [comment]
I started working on this earlier tonight. I should have a PR open within an hour.

**Comment by twolfson** [comment]
Styling preview: ![selection_142](https://cloud.githubusercontent.com/assets/902488/8348503/7d9418e6-1ad9-11e5-9bd3-c23404b488a0.png)

**Comment by twolfson** [comment]
#92 has been opened which will add notification badges :tada:

**Comment by twolfson** [comment]
This has been fixed by #92 and released in `2.4.0`.
