### ISSUE TITLE
Add avatar for `slack-for-linux` organization

### ISSUE THREAD

**Issue by twolfson** [plaidchat/plaidchat#61]
We have an organization! Woo hoo! We should make an avatar for it's organization page:

https://github.com/slack-for-linux

We should be able to use the Slack logo as long as we are clear we are unaffiliated:

https://my.slack.com/brand-guidelines

If you have any idea for an avatar, please post them here (text descriptions are fine but pictures are better).

**Comment by twolfson** [comment]
My initial thought was a monochrome Slack hash but I feel like that might be non-obvious for being separate.

My second thought is a Tux penguin with a Slack hash in on it's belly but I need to re-read the Slack guidelines to see if that's allowed.

**Comment by wlaurance** [comment]
Oh hehe,

Already had something in the works
ᐧ

**Comment by twolfson** [comment]
Cool, I look forward to seeing what you come up with =) I am by no means stuck to those initial suggestions.

**Comment by wlaurance** [comment]
I originally had the Slack square logo with Tux on it.

But since Tux's belly is white, we can put a colored hash logo on it. It will have to be pretty small do conform to the safety space requirement.

**Comment by wlaurance** [comment]
@twolfson This could be the start? https://github.com/slack-for-linux/slack-for-linux/blob/organization-logo/logo/slack-for-linux-tux-512x512.png

**Comment by twolfson** [comment]
Looks good at a large resolution. I am curious how it does at 30x30 and 70x70.

**Comment by twolfson** [comment]
Another thing to play with might be trying a monochrome tux but I think they all work fine.

https://daveden.files.wordpress.com/2013/02/tux.jpg

**Comment by wlaurance** [comment]
At 70x70 it is OK. You can still see the hash mark. But at 30x30, no way.

**Comment by twolfson** [comment]
How about a speech bubble with the Slack logo inside it or maybe the text "slack"?

https://thenounproject.com/term/speech-bubble/83662/

https://thenounproject.com/term/speech-bubbles/83663/

**Comment by twolfson** [comment]
Or maybe a black background with white CLI prompt with the Slack logo?

```
> #
```

or 

```
$ #
```

or

```
# _
```

where `#` is the Slack logo.

**Comment by wlaurance** [comment]
I like the idea of it being a CLI prompt. I vote for "$ #"

**Comment by twolfson** [comment]
I won't be free to play around with this until the weekend. Feel free to take a shot at it in the interim.

**Comment by wlaurance** [comment]
But then again, having the # icon for the CLI prompt is pretty cool.

**Comment by twolfson** [comment]
With design (e.g. visual, UX), it's always a good idea to try lots of things to see what works/what doesn't work. We should try all of the variations (and maybe think of some new ones while doing it).

**Comment by twolfson** [comment]
I decided to play around with our options. I am using Ubuntu Mono for now as the typeface:

![$#](https://cloud.githubusercontent.com/assets/902488/7877866/cfda3ebc-05a5-11e5-92f2-3c1c4c784b28.png)
![>#](https://cloud.githubusercontent.com/assets/902488/7877869/d39c3244-05a5-11e5-8222-44a02f91e123.png)
![#_](https://cloud.githubusercontent.com/assets/902488/7877868/d1b35db8-05a5-11e5-9c98-a31e2d8472ae.png)
![`#`](https://cloud.githubusercontent.com/assets/902488/7877871/d52701ca-05a5-11e5-9c99-dd5772af7d0f.png)

**Comment by twolfson** [comment]
Here are their 70x70 and 30x30 variants:

```bash
ls *.png | parallel convert {1} -resize 30x30 {1}.30.png
ls *.png | parallel convert {1} -resize 70x70 {1}.70.png
```

![angle_hash png 70](https://cloud.githubusercontent.com/assets/902488/7877984/69200f7e-05a7-11e5-8925-8f7a79d8298e.png)

![backtick_hash png 70](https://cloud.githubusercontent.com/assets/902488/7877996/766cd496-05a7-11e5-92d3-c7fb68033e1c.png)

![dollar_hash png 70](https://cloud.githubusercontent.com/assets/902488/7877995/766bf7b0-05a7-11e5-98d9-3b8b67994072.png)

![hash_underscore png 70](https://cloud.githubusercontent.com/assets/902488/7877997/766e7864-05a7-11e5-884e-ea6e76e0b62d.png)

![angle_hash png 30](https://cloud.githubusercontent.com/assets/902488/7877985/6921ab68-05a7-11e5-95ab-487c0582af17.png)

![backtick_hash png 30](https://cloud.githubusercontent.com/assets/902488/7877994/766bda3c-05a7-11e5-8c42-8d7ab6629d80.png)

![dollar_hash png 30](https://cloud.githubusercontent.com/assets/902488/7877998/7670114c-05a7-11e5-8b01-09efd75170af.png)

![hash_underscore png 30](https://cloud.githubusercontent.com/assets/902488/7877993/766bc04c-05a7-11e5-9fa6-bc3f4aad2859.png)

**Comment by twolfson** [comment]
With respect to the source files for the images (I am using SVGs via Inkscape as you did as well), where should we store them when we are ready? I am thinking an `assets` repo would probably be best since it isn't part of the package itself.

**Comment by twolfson** [comment]
I think the `$ #` looks the best and scales well.

**Comment by wlaurance** [comment]
Yes, let's start an assets repo under the same organization.

Does using the colored hash on the black background follow branding guidelines?

**Comment by twolfson** [comment]
Damn, you are right, it doesn't. Well, why do they provide the sticker then =(

I guess we will have to play with a white background and different colored text then (e.g. black `$`) or maybe try out that monochrome.

**Comment by twolfson** [comment]
Here are the monochrome variations:

![angle_hash](https://cloud.githubusercontent.com/assets/902488/7952794/0d45887c-0981-11e5-8702-e7042494cafd.png)

![backtick_hash](https://cloud.githubusercontent.com/assets/902488/7952796/0d489c7e-0981-11e5-82c9-2feb648abc28.png)

![dollar_hash](https://cloud.githubusercontent.com/assets/902488/7952795/0d484cb0-0981-11e5-8117-a10704fb0c60.png)

![hash_underscore](https://cloud.githubusercontent.com/assets/902488/7952797/0d4a2788-0981-11e5-8210-6fe05cb2f3ef.png)

![angle_hash png 70](https://cloud.githubusercontent.com/assets/902488/7952777/df35a688-0980-11e5-8c7e-53955a46d836.png)

![backtick_hash png 70](https://cloud.githubusercontent.com/assets/902488/7952781/df3a76a4-0980-11e5-9e5e-a0b9dddf1ab0.png)

![dollar_hash png 70](https://cloud.githubusercontent.com/assets/902488/7952782/df3b741e-0980-11e5-83f2-0627f536737b.png)

![hash_underscore png 70](https://cloud.githubusercontent.com/assets/902488/7952783/df48b08e-0980-11e5-9f35-541360c17880.png)

![angle_hash png 30](https://cloud.githubusercontent.com/assets/902488/7952778/df378b4c-0980-11e5-8e4c-243ff5cf257f.png)

![backtick_hash png 30](https://cloud.githubusercontent.com/assets/902488/7952780/df3a3c0c-0980-11e5-8345-c3a8c2d6a4e7.png)

![dollar_hash png 30](https://cloud.githubusercontent.com/assets/902488/7952779/df3802b6-0980-11e5-8b30-609341116aab.png)

![hash_underscore png 30](https://cloud.githubusercontent.com/assets/902488/7952784/df48e18a-0980-11e5-85de-9cbc85523f05.png)

**Comment by twolfson** [comment]
I thikn I prefer the `> #` in this grouping. The `$ #` reminds me of a telephone =/

**Comment by twolfson** [comment]
Here is the black on white swap:
![angle_hash](https://cloud.githubusercontent.com/assets/902488/7952873/454ef5ea-0982-11e5-8c73-d3fdccc30af8.png)

![backtick_hash](https://cloud.githubusercontent.com/assets/902488/7952875/45508fcc-0982-11e5-9ef3-1d2cda53b3ec.png)

![dollar_hash](https://cloud.githubusercontent.com/assets/902488/7952881/455bcafe-0982-11e5-95b0-856160fa280d.png)

![hash_underscore](https://cloud.githubusercontent.com/assets/902488/7952882/4560a48e-0982-11e5-8398-35e2639c4a78.png)

![angle_hash png 70](https://cloud.githubusercontent.com/assets/902488/7952874/4550369e-0982-11e5-80da-ee0055a0b950.png)

![backtick_hash png 70](https://cloud.githubusercontent.com/assets/902488/7952878/45538ab0-0982-11e5-9fa2-702d4e67ddd8.png)

![dollar_hash png 70](https://cloud.githubusercontent.com/assets/902488/7952879/455b4b1a-0982-11e5-98ec-5bcf68bed7ca.png)

![hash_underscore png 70](https://cloud.githubusercontent.com/assets/902488/7952884/4566474a-0982-11e5-997b-c338e267f0fc.png)

![angle_hash png 30](https://cloud.githubusercontent.com/assets/902488/7952876/4551883c-0982-11e5-8c7f-8937b4852f4b.png)

![backtick_hash png 30](https://cloud.githubusercontent.com/assets/902488/7952877/4552f4ec-0982-11e5-8710-80fe8554bd9e.png)

![dollar_hash png 30](https://cloud.githubusercontent.com/assets/902488/7952880/455b6078-0982-11e5-9c47-55af4b8e55b3.png)

![hash_underscore png 30](https://cloud.githubusercontent.com/assets/902488/7952883/4563678c-0982-11e5-8f2b-b718d98fdcb7.png)

**Comment by twolfson** [comment]
I feel like the white doesn't convey a programmer's context enough. My vote is still for white on black, this time with `> #` as my top pick.

**Comment by twolfson** [comment]
If you want to play around with the SVGs, they are editable in Inkscape in my branches in the `assets` repo:

https://github.com/slack-for-linux/assets/tree/twolfson/monochrome.white.avatars

https://github.com/slack-for-linux/assets/tree/twolfson/color.avatars

**Comment by dozoisch** [comment]
I would love a simple `#!`

**Comment by mathieumg** [comment]
> it might be too close to crunchbang dist logo

Though it's dead now.

**Comment by twolfson** [comment]
Now that we have a new name, I experimented with a few more avatar options:

![plaidchat](https://cloud.githubusercontent.com/assets/902488/8270353/7f45c5c0-17a2-11e5-9005-fdf22b263ed1.png)

![plaidchat-stroke](https://cloud.githubusercontent.com/assets/902488/8270356/7f481992-17a2-11e5-851a-65d24cc16825.png)

![plaidchat png 70](https://cloud.githubusercontent.com/assets/902488/8270354/7f466f98-17a2-11e5-8efa-f9d7790b25f0.png)

![plaidchat-stroke png 70](https://cloud.githubusercontent.com/assets/902488/8270357/7f500e90-17a2-11e5-947c-728d702e5399.png)

![plaidchat png 30](https://cloud.githubusercontent.com/assets/902488/8270355/7f4761f0-17a2-11e5-99ad-c6fa2c8d360c.png)

![plaidchat-stroke png 30](https://cloud.githubusercontent.com/assets/902488/8270358/7f50a4d6-17a2-11e5-80ce-ebade88f8ba4.png)

We will need to include attribution for these ones as I got the chat bubble and plaid scheme from The Noun Project:

- chat by Richard Schumann from the Noun Project
- plaid by Wes Breazell from the Noun Project

**Comment by twolfson** [comment]
Instead of scaling directly, we could create different logos for the smaller sizes which make the plaid more visible. For example:

![plaidchat-30](https://cloud.githubusercontent.com/assets/902488/8270366/56802940-17a3-11e5-9e55-f2444ab49848.png)

**Comment by wlaurance** [comment]
I like the filled in option.
