### ISSUE TITLE
Feature request: zoom window, like a browser can

### ISSUE THREAD

**Issue by eater** [plaidchat/plaidchat#77]
I like my Slack at about 80% of standard.

**Comment by twolfson** [comment]
TIL `nw.js` supports zooming: https://github.com/nwjs/nw.js/wiki/Window#windowzoomlevel

We can probably add this as a menu item with the same shortcuts as the browser (e.g. `ctrl++` and `ctrl+-`)

**Comment by rosshadden** [comment]
Observing system DPI value is another option to consider, though it would not be dynamic like zooming a webpage is.  I think the proposed zoom feature will cover all bases, I'm just mentioning DPI for completeness.

Worth noting that Chrome observes the DPI value and uses it, so chrome on my HiDPI computer is sized correctly.  That said, it's probably a bit more complicated to do.

**Comment by allanbreyes** [comment]
Fixing this is totally beyond me, but as a temporary patch, you can use a Chrome flag to launch with:

`plaidchat --force-device-scale-factor=2`

**Comment by twolfson** [comment]
#119 is now up to repair this issue

**Comment by twolfson** [comment]
This has been added/landed in `2.12.0`
