### ISSUE TITLE
Some News

### ISSUE THREAD

**Issue by wlaurance** [plaidchat/plaidchat#79]
Hi Everyone,

So we have some news about Slack's brand guidelines.

Unfortunately we are not allowed to use the word "Slack" in our product name.

Below is some information from Slack Headquarters.

1. Please remove "Slack" from your product name. You can give it whatever product name you want and then append "a Linux client for Slack", but the product itself should not feature our product name.

2. Please do not feature our Slack logo (or slight variations of it) as your product logo.

3. Please include the following messaging - "not created by, affiliated with, or supported by Slack Technologies, Inc." - where others would go to download the app.

4. Once the product name is changed, it would be great to also change the project name / repo on github to align with the new name, rather than including Slack.

We'll need to make some changes to the name and invent our own logo.

We need to act quickly by Monday June 15th or I believe their will be a more formal request arriving.

So, anyone have thoughts for a name?

**Comment by mathieumg** [comment]
If only they put time into actually developing a decent Linux client themselves rather than sending lawyers after you...

You're actually *helping* them and this is what they do.

**Comment by wlaurance** [comment]
A while back when we switched over to the new organization, I reached out to Slack to see if they would link to our repo because they didn't have a "real" Linux Client. I feel silly for reaching out now, but certainly they've known about this repo?

Anyways, I'll post the full dialogue because I want to be transparent about this.

--------------------------------------------------------------------------

 Will Laurance

May 28, 10:39 AM

Hi,

I am one of the maintainers of the slack-for-linux github project.

We have just moved to a new organization, https://github.com/slack-for-linux/slack-for-linux as a big push to grow contributions to the project.

Will you add a link to our project to your "Getting Started" guide?

This will give us a ton of traffic to the project and make happy Linux
slack users.

Thanks!

~Will Laurance

-----------------------------------------------------------------------------------------------------

 Jamie Rosenfield (Slack)

May 28, 12:45 PM

Hi Will,

It's really exciting what you all have been working on for Slack Linux users. I think it will make a lot of people happy. I did want to let you know that our team is working on a Linux app as a side project. I'm not sure the exact timing it to go into Beta and if it will ever be made a fully supported app at Slack, but wanted to give you that heads up. Regardless, we encourage our users to utilize our API and build interesting projects from it, and yours certainly falls within that realm.

One thing to note is our Brand Guidelines (https://www.slack.com/brand-guidelines). Because we need to ensure no potential users get confused as to who is creating and supporting 3rd party applications, we do need to ask that you make some changes:

    Please remove "Slack" from your product name. You can give it whatever product name you want and then append "a Linux client for Slack", but the product itself should not feature our product name.

    Please do not feature our Slack logo (or slight variations of it) as your product logo.

    Please include the following messaging - "not created by, affiliated with, or supported by Slack Technologies, Inc." - where others would go to download the app.

    Once the product name is changed, it would be great to also change the project name / repo on github to align with the new name, rather than including Slack.

I want to stress that we in no way want to hinder the work that you are doing. All above requests are just put in place to eliminate user confusion on who owns and supports the application being built.

We also will not be able to drive users to your app from our Getting Started page but I will pass the information along to our Integrations team so see if there are other areas of the site we can include a link!

Please let me know if you have any questions and good luck!!!

Jamie

Follow us on Twitter: @slackhq for tips, announcements, and the Slack #changelog

----------------------------------------------------------------------------------------------------------------------------------------

 	

Jamie Rosenfield (Slack)

Jun 10, 11:49 AM

Hi Will,

Just wanted to follow up on my previous message. Have you been able to make the requested changes? If not, please do so by Monday June15th.

Thank you,
Jamie

----------------------------------------------------------------------------------------------------------------------------------

10:40 AM (8 minutes ago)
		
to Slack
Hi Jamie,

I've made it an issue on the repo and we should have the items resolved by the 15th.

Thanks,

Will

-----------------------------------------------------------------------------------------------------------------------------------

**Comment by twolfson** [comment]
Ah, neat. Glad to hear this wasn't an out of the blue "Cease and desist"-esque thread but more that we want to respect each others boundaries. Any ideas on the new name?

**Comment by dozoisch** [comment]
Slux? or why not just going with  "a Linux client for Slack" ? Don't know if that is against their guidelines

**Comment by twolfson** [comment]
@dozoisch We have a thread about avatars, see #61. Feel free to throw yours into the thread =)

@wlaurance Can you ask them if any of the avatars in #61 are acceptable for "Please do not feature our Slack logo (or slight variations of it) as your product logo."? From the brand guidelines, I am pretty sure they are but want to make sure.

**Comment by twolfson** [comment]
More name ideas: hashchat, octothorpe

**Comment by twolfson** [comment]
Ah, damn. hashchat is already taken =(

**Comment by bronzdoc** [comment]
I like Slux =)

**Comment by twolfson** [comment]
Another idea: plaidchat

**Comment by thekev** [comment]
call it "bob" and use bob dobbs as the logo. "bob" is the personification of all that is slack. and I guarantee the church of the subgenius won't send lawyers after you.

**Comment by twolfson** [comment]
Sooo, it's June 15 now with ~4.5 hours left until 11:59PM PST. We should prob rename very soon =/

**Comment by wlaurance** [comment]
Slux is already taken in the npm world.

+1 for plaidchat

**Comment by twolfson** [comment]
I started freewriting but didn't get far =/

https://gist.github.com/twolfson/a9e013ec6d38d3821c4e

**Comment by twolfson** [comment]
Let's do plaidchat. @wlaurance I will take care of the renames this time =P

**Comment by wlaurance** [comment]
Sounds good @twolfson 

Anymore renames, I say we invest a writing a script =P

**Comment by twolfson** [comment]
Hehe. Here's to hoping this is the last of them :beers: 

I have renamed the org/repo. I will cowboy PR/commit the Travis CI references and whatnot.

**Comment by twolfson** [comment]
Also, we should prob put up a notice on the original `slack-for-linux` on `npm`.

**Comment by twolfson** [comment]
Here's a checklist:

- [x] Rename organization
- [x] Rename repo
- [ ] Update README/docs references
- [ ] Publish latest version to `npm`
- [ ] Add back all `npm` owners to `npm`
- [ ] Publish updated README on `npm`
- [ ] Create test PR to verify Travis CI hooks are working

**Comment by twolfson** [comment]
@wlaurance One thing that I have no control over is your Analytics beacon. You will need to change that one in the README =/

**Comment by twolfson** [comment]
We are live on `npm` :tada:

https://www.npmjs.com/package/plaidchat

**Comment by twolfson** [comment]
As a heads up, the notice I am publishing to `npm` for `slack-for-linux` can be found here:

https://github.com/plaidchat/plaidchat/tree/dev/slack-for-linux.npm.notice

**Comment by twolfson** [comment]
Aaaand posted:

https://www.npmjs.com/package/slack-for-linux

**Comment by twolfson** [comment]
Travis CI is taking a bit of time to pick up the new organization. All of the other tasks are done so I am going to close this issue. Thanks for the support everyone =D
