### ISSUE TITLE
Set default window size

### ISSUE THREAD

**Issue by NeilHanlon** [plaidchat/plaidchat#83]
When opening the window in Gnome3 on Debian 8 (And Fedora 22), the window opens in a small square. Some sort of option (command line, config file, whatever) would be great so we can specify the size we want the window to open in. Also--maximize would be good.

**Comment by twolfson** [comment]
This seems like a reasonable request. I think we will have to convert the existing `index.html` into more of a sub-window launcher for this to work but that should be simple enough.
