### ISSUE TITLE
On desktop notification the App Crashes

### ISSUE THREAD

**Issue by JuanCrg90** [plaidchat/plaidchat#86]
Hi, i have a problem. When i receive a desktop notification, the app crashes, in the console does not appear any message

I read this issue and update my browser but the problem continues
https://github.com/plaidchat/plaidchat/issues/76

Information about OS:
npm --version: 2.11.3
node --version: v0.12.4
OS: 4.0.5-1-ARCH
Gnome Shell 3.16.2
Chrome Versión 43.0.2357.130 (64-bit)
slack-for-linux Version 2.0.1

Regards.

**Comment by twolfson** [comment]
After upgrading your browser, did you uninstall and reinstall `plaidchat`?

```bash
npm uninstall -g plaidchat
npm install -g plaidchat
```

**Comment by JuanCrg90** [comment]
Thank you, I had not uninstalled. i'm uninstall and reinstall now works.

Maybe it would be feasible to add a FAQ for situations like this :smiley:

**Comment by twolfson** [comment]
Glad to hear it works =) I agree, I initially didn't think this would be a common occurrence but I could see an FAQ being useful. I will leave this issue open until we add it.

**Comment by JuanCrg90** [comment]
Nice, thank you for the help.

**Comment by twolfson** [comment]
I have opened up #88 to patch this issue. Thanks for the bug report =)

**Comment by twolfson** [comment]
We have added the new FAQ in `2.2.1`. Thanks again for the bug report! =)
