### ISSUE TITLE
Add keyboard shortcut to show/hide the team bar

### ISSUE THREAD

**Issue by distracteddev** [plaidchat/plaidchat#87]
The team bar is rarely accessed, and most probably just use the cmd+1, cmd+2  shortcuts. This will allow us to free up some of that valuable horizontal screen space.

**Comment by twolfson** [comment]
I am open to supporting this. Do you know if the official Slack clients have this shortcut/what it's Linux equivalent would be?

**Comment by mathieumg** [comment]
I do not see the equivalent in the Windows version. However, it's more useful there because it has notification badges on organization logos.

**Comment by distracteddev** [comment]
No, unfortunately, the official slack client does not support a show/hide feature.

**Comment by twolfson** [comment]
@mathieumg Notification badges are planned in #39 but we were mostly waiting on the React refactor before adding more features to port

@distracteddev Hmm, that makes me more hesitant on this feature then =/

If we were to add that feature, the current sort order between teams for the sidebar is based on load order. I imagine that if we added this, then we would want something more consistent (e.g. alphabetical). Any idea what order the official clients sort teams by?

**Comment by mathieumg** [comment]
> Notification badges are planned in #39 but we were mostly waiting on the React refactor before adding more features to port

Yeah I think I saw that, thanks for the reminder! :)

> Any idea what order the official clients sort teams by?

I think it's the order you added the teams in, by default, but it can easily be overridden through drag and drop of the team icons.

**Comment by twolfson** [comment]
@mathieumg Ah, alright. Thanks for the info =) I guess we will have to refine how we manage that data in future PRs =)

**Comment by RoelVdP** [comment]
+1 for hide/show team toolbar functionality, either via menu or via shortcut. It will give extra screenwidth
