### ISSUE TITLE
Spelling check is not working

### ISSUE THREAD

**Issue by chethan-K** [plaidchat/plaidchat#89]
Hey team,

Nice app, Can you please look around for spelling check ..?

Thanks
Chethan K

**Comment by twolfson** [comment]
It looks like this is supported in nw.js@0.13.

https://github.com/nwjs/nw.js/issues/332

Unfortunately, those releases are still in alpha so we will have to wait until it's stable/listed here:

https://github.com/nwjs/nw.js/releases
